package pl.liarek123.mt2core.types;

public enum Items {
    NINJA_ARMOR1,
    NINJA_ARMOR2,
    NINJA_ARMOR3,
    NINJA_ARMOR4,
    NINJA_ARMOR5,
    WARRIOR_ARMOR1,
    WARRIOR_ARMOR2,
    WARRIOR_ARMOR3,
    WARRIOR_ARMOR4,
    WARRIOR_ARMOR5;
}
